Closes #114
rebelstackio/yakchat pull request #115
Opened 2019-04-12 18:46 UTC by oreyes1991

Remove firebase from npm Dependencies insted use the CDN for both front-script and backofficce

# the build files size now
- frontscript.js = 271KiB
- main.js(backoffice) = 329 KiB

2019-04-12 19:01 UTC, jegj requested changes

2019-04-12 19:01 UTC, jegj commented on front-script/package.json
> -		"firebase": "^5.7.2",
i think in the case of the frontscript we don't have choice to put firebase as CDN ... otherwise we need to force to put the CDN in the client web page . At leats you have something in mind ..

2019-04-12 19:01 UTC, jegj commented on front-script/public/index.html
> +	<script src="https://www.gstatic.com/firebasejs/5.8.4/firebase.js"></script>
this index.html file doesn't belong in the frontscript release it represents the clients web page ... it's for testing purpose

2019-04-12 19:04 UTC, oreyes1991 commented on front-script/package.json
> -		"firebase": "^5.7.2",
oh yeah, we could put it in the embed code?, to avoid the frontscript be so large?

2019-04-12 19:11 UTC, oreyes1991 commented on front-script/package.json
> -		"firebase": "^5.7.2",
the embed code will end up like this
```
<script src="https://www.gstatic.com/firebasejs/5.8.4/firebase.js"></script>
<script src="https://rebelstackio.github.io/yakchat/frontscript.js"></script>
```

2019-04-12 19:26 UTC, oreyes1991 commented on backoffice/src/components/editchannel/index.js
> +				this.embendCode = `<script src="https://www.gstatic.com/firebasejs/5.8.4/firebase.js"></script><script src="https://rebelstackio.github.io/yakchat/frontscript.js"></script>`;
@jegj here now im including the firebase cdn

2019-04-12 20:22 UTC, jegj approved these changes

2019-04-16 21:46 UTC, pablolimo approved these changes

2019-04-16 21:47 UTC, merged