Feature/#visitorsfunctions, Feature/#clientchat, Feature/#visitorchat
rebelstackio/yakchat pull request #82
Opened 2019-03-13 19:18 UTC by oreyes1991

this will create the firebase cloud function to handle visitors and registrant,

add chat between registrant/visitor and client owner of that channel,
list all the registrant/visitor in the client's channel

2019-03-14 11:54 UTC, jegj requested changes
Request a dummy change

2019-03-14 11:54 UTC, jegj commented on functions/functions/package.json
> +  "engines": { "node": "8" }
should be 10....

2019-03-14 19:22 UTC, pablolimo approved these changes

2019-03-15 02:33 UTC, jegj approved these changes

2019-03-15 02:33 UTC, merged